import { Archive, CalendarRange, CopyPlus, Plus, RotateCcw } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { api, ApiError } from '../../api'
import { useAuth } from '../../auth'
import { TrainingProgramDetail, TrainingProgramList, TrainingProgramSummary } from '../../types'
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, Modal, SearchField, SelectInput, StatusNotice } from '../ui'
import { ProgrammingShell } from './ProgrammingShell'

const PAGE_SIZE = 12

export function ProgramLibrary() {
  const { user } = useAuth(); const navigate = useNavigate(); const cache = useQueryClient()
  const [status, setStatus] = useState('active'); const [publication, setPublication] = useState('all'); const [goal, setGoal] = useState('all'); const [search, setSearch] = useState(''); const [page, setPage] = useState(1)
  const [archiveTarget, setArchiveTarget] = useState<TrainingProgramSummary | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const query = useQuery({ queryKey: ['training-programs', status], queryFn: () => api<TrainingProgramList>(`/coach/training-programs?status=${status}&page=1&per_page=100`) })
  const source = useMemo(() => query.data?.items ?? [], [query.data]); const goals = useMemo(() => [...new Set(source.flatMap(item => item.goal_tags))].sort(), [source])
  const filtered = useMemo(() => source.filter(item => (publication === 'all' || (publication === 'draft' ? item.has_draft : item.current_published_version_number !== null)) && (goal === 'all' || item.goal_tags.includes(goal)) && (!search.trim() || item.name.toLowerCase().includes(search.trim().toLowerCase()))), [goal, publication, search, source])
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, pages); const rows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE)
  function update(setter: (value: string) => void, value: string) { setter(value); setPage(1) }
  function reset() { setPublication('all'); setGoal('all'); setSearch(''); setPage(1) }
  async function action(item: TrainingProgramSummary, name: 'revisions' | 'archive') { setBusy(item.id); setError(''); try { const next = await api<TrainingProgramDetail>(`/coach/training-programs/${item.id}/${name}`, { method: 'POST' }); cache.setQueryData(['training-program', item.id], next); await cache.invalidateQueries({ queryKey: ['training-programs'] }); setArchiveTarget(null); if (name === 'revisions') navigate(`/coach/programming/programs/${item.id}`) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'The program action could not be completed.') } finally { setBusy('') } }
  return <ProgrammingShell title="Programs" description="Create reusable multi-week structures pinned to exact published workout versions." action={user?.is_demo ? <Button disabled title="Demo workspace — changes are disabled"><Plus aria-hidden="true" className="size-4" />New program</Button> : <Link to="/coach/programming/programs/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white hover:bg-primary-hover"><Plus aria-hidden="true" className="size-4" />New program</Link>}>
    {error && <StatusNotice tone="risk" title="Program action unsuccessful">{error}</StatusNotice>}
    <Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(14rem,1.5fr)_repeat(3,minmax(10rem,1fr))]"><SearchField value={search} onChange={value => update(setSearch, value)} label="Search programs" /><Filter label="Program status" value={status} onChange={value => update(setStatus, value)} options={[['active', 'Active'], ['archived', 'Archived']]} /><Filter label="Publication status" value={publication} onChange={value => update(setPublication, value)} options={[['all', 'Draft and published'], ['draft', 'Has draft'], ['published', 'Published only']]} /><Filter label="Goal tag" value={goal} onChange={value => update(setGoal, value)} options={[['all', 'All goal tags'], ...goals.map(value => [value, value.replaceAll('_', ' ')])]} /></div></Card>
    {query.isLoading ? <LoadingState label="Loading programs" /> : query.error ? <ErrorState title="Programs unavailable" description={query.error.message} onRetry={() => query.refetch()} /> : !rows.length ? <EmptyState icon={CalendarRange} title="No programs match" description={source.length ? 'Adjust the status, publication, goal, or search filters.' : status === 'archived' ? 'No programs have been archived.' : 'Create the first reusable multi-week program.'} action={source.length ? <Button variant="secondary" onClick={reset}><RotateCcw aria-hidden="true" className="size-4" />Clear filters</Button> : undefined} /> : <><p className="text-sm text-secondary" aria-live="polite">Showing {(safePage - 1) * PAGE_SIZE + 1}–{Math.min(safePage * PAGE_SIZE, filtered.length)} of {filtered.length} programs</p><div className="grid gap-4 xl:grid-cols-2">{rows.map(item => <ProgramCard key={item.id} item={item} demo={Boolean(user?.is_demo)} busy={busy === item.id} onRevision={() => action(item, 'revisions')} onArchive={() => setArchiveTarget(item)} />)}</div>{pages > 1 && <nav aria-label="Program pages" className="flex items-center justify-center gap-3"><Button variant="secondary" disabled={safePage === 1} onClick={() => setPage(safePage - 1)}>Previous</Button><span className="text-sm text-secondary">Page {safePage} of {pages}</span><Button variant="secondary" disabled={safePage === pages} onClick={() => setPage(safePage + 1)}>Next</Button></nav>}</>}
    <Modal open={Boolean(archiveTarget)} onClose={() => setArchiveTarget(null)} title="Archive training program?" description="It will leave active selection while every published version remains readable."><p className="text-sm text-secondary">{archiveTarget?.name}</p><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={() => setArchiveTarget(null)}>Cancel</Button><Button variant="danger" loading={busy === archiveTarget?.id} onClick={() => archiveTarget && action(archiveTarget, 'archive')}>Archive program</Button></div></Modal>
  </ProgrammingShell>
}

function ProgramCard({ item, demo, busy, onRevision, onArchive }: { item: TrainingProgramSummary; demo: boolean; busy: boolean; onRevision: () => void; onArchive: () => void }) { return <Card as="article" className="flex flex-col"><div className="flex flex-wrap gap-2"><Badge tone={item.has_draft ? 'attention' : 'positive'}>{item.has_draft ? 'Draft available' : 'Published'}</Badge>{item.current_published_version_number && <Badge tone="info">Published v{item.current_published_version_number}</Badge>}{item.status === 'archived' && <Badge>Archived</Badge>}</div><h2 className="mt-3 text-xl font-semibold">{item.name}</h2><div className="mt-3 grid grid-cols-2 gap-3 rounded-xl bg-elevated p-3 text-sm sm:grid-cols-4"><Metric label="Duration" value={`${item.duration_weeks} weeks`} /><Metric label="Workouts" value={item.workout_slot_count} /><Metric label="Deloads" value={item.deload_week_count} /><Metric label="Updated" value={new Date(item.updated_at).toLocaleDateString()} /></div><div className="mt-3 flex flex-wrap gap-2">{item.goal_tags.map(tag => <Badge key={tag}>{tag.replaceAll('_', ' ')}</Badge>)}</div><div className="mt-auto flex flex-wrap gap-2 pt-5"><Link to={`/coach/programming/programs/${item.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-semibold text-white">{item.has_draft ? 'Open draft' : 'View published version'}</Link>{item.status === 'active' && !item.has_draft && item.current_published_version_number && <Button variant="secondary" loading={busy} disabled={demo} onClick={onRevision}><CopyPlus aria-hidden="true" className="size-4" />Create revision</Button>}{item.status === 'active' && <Button variant="ghost" disabled={demo || busy} onClick={onArchive}><Archive aria-hidden="true" className="size-4" />Archive</Button>}</div></Card> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <SelectInput aria-label={label} className="mt-0" value={value} onChange={event => onChange(event.target.value)}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectInput> }
