import { CalendarDays, Gauge } from 'lucide-react'
import { ProgramTemplateVersionSummary, TrainingProgramDraftData } from '../../types'
import { Badge, Card } from '../ui'

const weekdays = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'] as const

export function ProgramPreview({ program, templates }: { program: TrainingProgramDraftData; templates: Map<string, ProgramTemplateVersionSummary> }) {
  return <div aria-label="Trainee program preview" className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-primary">Trainee preview</p><h2 className="mt-1 text-2xl font-semibold">{program.name || 'Untitled program'}</h2><div className="mt-3 flex flex-wrap gap-2"><Badge tone="info"><CalendarDays aria-hidden="true" className="mr-1 size-3" />{program.duration_weeks} weeks</Badge>{program.goal_tags.map(tag => <Badge key={tag}>{tag.replaceAll('_', ' ')}</Badge>)}</div>{program.trainee_instructions && <p className="mt-4 text-sm leading-6 text-secondary">{program.trainee_instructions}</p>}</div>{program.weeks.map(week => <section key={week.week_number} aria-labelledby={`program-preview-week-${week.week_number}`} className={`rounded-xl border p-4 ${week.is_deload ? 'border-[rgb(var(--status-attention-border))] bg-[rgb(var(--status-attention-bg))]' : 'bg-surface'}`}><div className="flex flex-wrap items-center gap-2"><h3 id={`program-preview-week-${week.week_number}`} className="text-lg font-semibold">Week {week.week_number}{week.label ? ` · ${week.label}` : ''}</h3>{week.is_deload && <Badge tone="attention">Coach-authored deload</Badge>}</div>{week.is_deload && <p className="mt-2 text-xs leading-5 text-secondary">Your coach marked this week as a deload; the system does not change workouts automatically.</p>}<div className="mt-4 space-y-4">{weekdays.map(day => { const sessions = week.sessions.filter(item => item.weekday === day).sort((a, b) => a.display_order - b.display_order); if (!sessions.length) return null; return <div key={day}><h4 className="text-xs font-bold uppercase tracking-wide text-muted">{day}</h4><div className="mt-2 space-y-2">{sessions.map(session => { const template = templates.get(session.workout_template_version_id); const duration = session.planned_duration_override_minutes ?? template?.estimated_duration_minutes; const rpe = session.target_session_rpe_override ?? template?.target_session_rpe; return <Card key={`${day}-${session.display_order}`} as="article" className="shadow-none"><div className="flex flex-wrap items-center gap-2"><h5 className="font-semibold">{template?.name ?? 'Workout unavailable'}</h5><Badge tone={session.required ? 'info' : 'neutral'}>{session.required ? 'Required' : 'Optional'}</Badge></div><div className="mt-2 flex flex-wrap gap-2 text-xs text-muted">{duration && <span>{duration} min</span>}{rpe !== null && rpe !== undefined && <span className="inline-flex items-center gap-1"><Gauge aria-hidden="true" className="size-3" />Target RPE {rpe}</span>}</div>{session.trainee_instructions && <p className="mt-2 text-sm leading-6 text-secondary">{session.trainee_instructions}</p>}</Card> })}</div></div> })}{!week.sessions.length && <p className="text-sm text-muted">Rest week — no workouts planned.</p>}</div></section>)}</div>
}
