import { Archive, Clock3, CopyPlus, LayoutTemplate, Plus, RotateCcw } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useNavigate } from 'react-router-dom'
import { api, ApiError } from '../../api'
import { useAccountQueryScope, useAuth } from '../../auth'
import { WorkoutTemplateDetail, WorkoutTemplateList, WorkoutTemplateSummary } from '../../types'
import { Badge, Button, Card, EmptyState, ErrorState, LoadingState, Modal, SearchField, SelectInput, StatusNotice } from '../ui'
import { ProgrammingShell } from './ProgrammingShell'
import { TemplateStatusBadge } from './ProgrammingBadges'

const PAGE_SIZE = 12

export function TemplateLibrary() {
  const { user } = useAuth(); const scope = useAccountQueryScope(); const navigate = useNavigate(); const cache = useQueryClient()
  const [status, setStatus] = useState('active'); const [publication, setPublication] = useState('all'); const [goal, setGoal] = useState('all'); const [search, setSearch] = useState(''); const [page, setPage] = useState(1)
  const [archiveTarget, setArchiveTarget] = useState<WorkoutTemplateSummary | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const query = useQuery({ queryKey: [...scope, 'workout-templates', status], queryFn: () => api<WorkoutTemplateList>(`/coach/workout-templates?status=${status}&page=1&per_page=100`) })
  const source = useMemo(() => query.data?.items ?? [], [query.data]); const goals = useMemo(() => [...new Set(source.flatMap(item => item.goal_tags))].sort(), [source])
  const filtered = useMemo(() => source.filter(item => (publication === 'all' || (publication === 'draft' ? item.has_draft : !item.has_draft && item.current_published_version_number !== null)) && (goal === 'all' || item.goal_tags.includes(goal)) && (!search.trim() || item.name.toLowerCase().includes(search.trim().toLowerCase()))), [goal, publication, search, source])
  const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE)); const safePage = Math.min(page, pages); const rows = filtered.slice((safePage - 1) * PAGE_SIZE, safePage * PAGE_SIZE)
  function update(setter: (value: string) => void, value: string) { setter(value); setPage(1) }
  function reset() { setPublication('all'); setGoal('all'); setSearch(''); setPage(1) }
  async function action(item: WorkoutTemplateSummary, actionName: 'revisions' | 'archive') { setBusy(item.id); setError(''); try { const next = await api<WorkoutTemplateDetail>(`/coach/workout-templates/${item.id}/${actionName}`, { method: 'POST' }); cache.setQueryData([...scope, 'workout-template', item.id], next); await cache.invalidateQueries({ queryKey: [...scope, 'workout-templates'] }); setArchiveTarget(null); if (actionName === 'revisions') navigate(`/coach/programming/templates/${item.id}`) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'The template action could not be completed.') } finally { setBusy('') } }

  return <ProgrammingShell title="Workout templates" description="Author reusable workout prescriptions, review trainee-facing content, and publish immutable versions." action={user?.is_demo ? <Button disabled><Plus aria-hidden="true" className="size-4" />New template</Button> : <Link to="/coach/programming/templates/new" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white hover:bg-primary-hover"><Plus aria-hidden="true" className="size-4" />New template</Link>}>
    {error && <StatusNotice tone="risk" title="Template action unsuccessful">{error}</StatusNotice>}
    <Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-[minmax(14rem,1.5fr)_repeat(3,minmax(10rem,1fr))]"><SearchField value={search} onChange={value => update(setSearch, value)} label="Search workout templates" /><Filter label="Template status" value={status} onChange={value => update(setStatus, value)} options={[['active', 'Active'], ['archived', 'Archived']]} /><Filter label="Publication status" value={publication} onChange={value => update(setPublication, value)} options={[['all', 'Draft and published'], ['draft', 'Has draft'], ['published', 'Published only']]} /><Filter label="Goal tag" value={goal} onChange={value => update(setGoal, value)} options={[['all', 'All goal tags'], ...goals.map(value => [value, value.replaceAll('_', ' ')])]} /></div></Card>
    {query.isLoading ? <LoadingState label="Loading workout templates" /> : query.error ? <ErrorState title="Workout templates unavailable" description={query.error.message} onRetry={() => query.refetch()} /> : !rows.length ? <EmptyState icon={LayoutTemplate} title="No templates match" description={source.length ? 'Adjust the status, publication, goal, or search filters.' : status === 'archived' ? 'No templates have been archived.' : 'Create the first reusable workout template.'} action={source.length ? <Button variant="secondary" onClick={reset}><RotateCcw aria-hidden="true" className="size-4" />Clear filters</Button> : undefined} /> : <><p className="text-sm text-secondary" aria-live="polite">Showing {(safePage - 1) * PAGE_SIZE + 1}–{Math.min(safePage * PAGE_SIZE, filtered.length)} of {filtered.length} templates</p><div className="grid gap-4 xl:grid-cols-2">{rows.map(item => <TemplateCard key={item.id} item={item} demo={Boolean(user?.is_demo)} busy={busy === item.id} onRevision={() => action(item, 'revisions')} onArchive={() => setArchiveTarget(item)} />)}</div><Pagination page={safePage} pages={pages} onChange={setPage} /></>}
    <Modal open={Boolean(archiveTarget)} onClose={() => setArchiveTarget(null)} title="Archive workout template?" description="The template will leave active selection while all published history remains intact."><p className="text-sm text-secondary">{archiveTarget?.name}</p><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><Button variant="secondary" onClick={() => setArchiveTarget(null)}>Cancel</Button><Button variant="danger" loading={busy === archiveTarget?.id} onClick={() => archiveTarget && action(archiveTarget, 'archive')}>Archive template</Button></div></Modal>
  </ProgrammingShell>
}

function TemplateCard({ item, demo, busy, onRevision, onArchive }: { item: WorkoutTemplateSummary; demo: boolean; busy: boolean; onRevision: () => void; onArchive: () => void }) {
  const openLabel = item.has_draft ? 'Open draft' : 'View published version'
  return <Card as="article" className="flex flex-col"><div className="flex flex-wrap items-center gap-2"><TemplateStatusBadge status={item.status} hasDraft={item.has_draft} />{item.current_published_version_number && <Badge tone="info">Published v{item.current_published_version_number}</Badge>}</div><h2 className="mt-3 text-xl font-semibold">{item.name}</h2><div className="mt-3 grid grid-cols-2 gap-3 rounded-xl bg-elevated p-3 text-sm sm:grid-cols-4"><Metric label="Duration" value={item.estimated_duration_minutes ? `${item.estimated_duration_minutes} min` : 'Not set'} /><Metric label="Session RPE" value={item.target_session_rpe ?? 'Not set'} /><Metric label="Exercises" value={item.exercise_count} /><Metric label="Updated" value={new Date(item.updated_at).toLocaleDateString()} /></div><div className="mt-3 flex flex-wrap gap-2">{item.goal_tags.map(tag => <Badge key={tag}>{tag.replaceAll('_', ' ')}</Badge>)}</div>{item.published_at && <p className="mt-3 flex items-center gap-1.5 text-xs text-muted"><Clock3 aria-hidden="true" className="size-3.5" />Published {new Date(item.published_at).toLocaleString()}</p>}<div className="mt-auto flex flex-wrap gap-2 pt-5"><Link to={`/coach/programming/templates/${item.id}`} className="inline-flex min-h-11 items-center rounded-xl bg-primary px-4 text-sm font-semibold text-white">{openLabel}</Link>{item.status === 'active' && !item.has_draft && item.current_published_version_number && <Button variant="secondary" loading={busy} disabled={demo} onClick={onRevision}><CopyPlus aria-hidden="true" className="size-4" />Create revision</Button>}{item.status === 'active' && <Button variant="ghost" disabled={demo || busy} onClick={onArchive}><Archive aria-hidden="true" className="size-4" />Archive</Button>}</div></Card>
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div><p className="text-xs text-muted">{label}</p><p className="mt-1 font-semibold">{value}</p></div> }
function Filter({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <div><SelectInput aria-label={label} className="mt-0" value={value} onChange={event => onChange(event.target.value)}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</SelectInput></div> }
function Pagination({ page, pages, onChange }: { page: number; pages: number; onChange: (page: number) => void }) { if (pages <= 1) return null; return <nav aria-label="Template pages" className="flex items-center justify-center gap-3"><Button variant="secondary" disabled={page === 1} onClick={() => onChange(page - 1)}>Previous</Button><span className="text-sm text-secondary">Page {page} of {pages}</span><Button variant="secondary" disabled={page === pages} onClick={() => onChange(page + 1)}>Next</Button></nav> }
