import { FormEvent, useState } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { api, ApiError } from '../api'
import { useAuth } from '../auth'
import { AuthResponse } from '../types'

function AuthFrame({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="hidden bg-ink p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="font-black">FITNESS <span className="text-mint">INTELLIGENCE</span></div><div><p className="eyebrow !text-mint">Understand the baseline</p><h1 className="mt-4 max-w-xl text-5xl font-black leading-tight">Clear signals for better coaching decisions.</h1><p className="mt-5 max-w-lg text-lg text-white/65">Explainable scores, visible assumptions, and actionable review flags—without pretending to provide medical diagnosis.</p></div><p className="text-sm text-white/45">A coaching support platform. Not medical care.</p></section><section className="flex items-center justify-center p-5"><div className="w-full max-w-md"><p className="eyebrow">Welcome</p><h1 className="mt-2 text-4xl font-black">{title}</h1><p className="mt-2 text-black/60">{subtitle}</p><div className="mt-8">{children}</div></div></section></main>
}

export function LoginPage() {
  const { user, setSession } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to={user.role === 'coach' ? '/coach/dashboard' : '/trainee/dashboard'} replace />
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const form = new FormData(e.currentTarget); try { const auth = await api<AuthResponse>('/auth/login', { method: 'POST', body: JSON.stringify({ email: form.get('email'), password: form.get('password') }) }); setSession(auth); navigate(auth.user.role === 'coach' ? '/coach/dashboard' : '/trainee/dashboard') } catch (err) { setError(err instanceof ApiError ? err.message : 'Could not sign in') } finally { setBusy(false) } }
  return <AuthFrame title="Sign in" subtitle="Continue to your role-aware dashboard."><form onSubmit={submit} className="space-y-4"><label className="label">Email<input className="field" name="email" type="email" required autoComplete="email" defaultValue="trainee@fitness.example.com" /></label><label className="label">Password<input className="field" name="password" type="password" required autoComplete="current-password" defaultValue="DemoPass123!" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="btn-primary w-full">{busy ? 'Signing in…' : 'Sign in'}</button><p className="text-center text-sm text-black/60">New trainee? <Link className="font-bold text-moss" to="/register">Create an account</Link></p></form></AuthFrame>
}

export function RegisterPage() {
  const { user, setSession } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  if (user) return <Navigate to={user.role === 'coach' ? '/coach/dashboard' : '/trainee/dashboard'} replace />
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const f = new FormData(e.currentTarget); try { const auth = await api<AuthResponse>('/auth/register', { method: 'POST', body: JSON.stringify(Object.fromEntries(f)) }); setSession(auth); navigate('/onboarding') } catch (err) { setError(err instanceof ApiError ? err.message : 'Could not register') } finally { setBusy(false) } }
  return <AuthFrame title="Create trainee account" subtitle="Use your coach invite to establish the assignment."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><label className="label">First name<input className="field" name="first_name" required /></label><label className="label">Last name<input className="field" name="last_name" required /></label><label className="label sm:col-span-2">Email<input className="field" name="email" type="email" required /></label><label className="label sm:col-span-2">Password <span className="font-normal text-black/50">(10+ characters)</span><input className="field" name="password" type="password" minLength={10} required /></label><label className="label sm:col-span-2">Coach invite code<input className="field" name="invite_code" required defaultValue="FIT-DEMO-2026" /></label>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700 sm:col-span-2">{error}</p>}<button disabled={busy} className="btn-primary sm:col-span-2">{busy ? 'Creating…' : 'Create account'}</button><p className="text-center text-sm text-black/60 sm:col-span-2">Already registered? <Link className="font-bold text-moss" to="/login">Sign in</Link></p></form></AuthFrame>
}
