import { useEffect, useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { api, ApiError } from '../api'
import { Shell } from '../components'
import { Assessment, AssessmentData, HealthIndex } from '../types'

const num = (min: number, max: number) => z.preprocess(v => v === '' || Number.isNaN(v) ? undefined : v, z.number().min(min).max(max).optional())
const schema = z.object({
  age: num(16, 100), height_cm: num(100, 250), weight_kg: num(30, 350), selected_goal: z.string().optional(), target_weight_kg: num(30, 350), hydration_ml: num(0, 10000),
  sleep_hours: num(0, 16), sleep_quality: num(1, 5), wake_refreshed: z.boolean().optional(), daily_steps: num(0, 100000), activity_types: z.array(z.string()), activity_minutes_weekly: num(0, 5000),
  workout_frequency_weekly: num(0, 14), average_rpe: num(0, 10), workout_duration_minutes: num(0, 600), perceived_recovery: num(1, 5), stress_level: num(0, 10), resting_heart_rate: num(30, 220),
  palpitations: z.boolean(), shortness_of_breath: z.boolean(), chest_pain: z.boolean(), calorie_mode: z.string().optional(), calorie_target: num(800, 8000), calorie_intake: num(0, 10000), protein_target_g: num(0, 500), protein_intake_g: num(0, 500), carbohydrate_intake_g: num(0, 1500), healthy_fat_intake_g: num(0, 500), fruit_servings: num(0, 30), vegetable_servings: num(0, 30), fiber_g: num(0, 150), meal_consistency: num(1, 5),
})

const defaults: AssessmentData = { activity_types: [], palpitations: false, shortness_of_breath: false, chest_pain: false }
const required = ['age','height_cm','weight_kg','selected_goal','hydration_ml','sleep_hours','sleep_quality','wake_refreshed','daily_steps','activity_minutes_weekly','workout_frequency_weekly','average_rpe','stress_level','calorie_mode'] as const
const activityOptions = ['walking','running','swimming','cycling','hiit','strength_training','functional_training','pilates','yoga','sports','gardening','housework','stair_climbing','active_commuting']

function NumberField({ name, label, unit, min, max, optional = false, register, error }: { name: keyof AssessmentData; label: string; unit?: string; min: number; max: number; optional?: boolean; register: ReturnType<typeof useForm<AssessmentData>>['register']; error?: string }) {
  return <label className="label">{label} {unit && <span className="font-normal text-black/50">({unit})</span>} {optional && <span className="font-normal text-black/40">optional</span>}<input className="field" type="number" step="any" min={min} max={max} {...register(name, { valueAsNumber: true })} />{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>
}

export function OnboardingPage() {
  const navigate = useNavigate(); const [step, setStep] = useState(0); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true)
  const form = useForm<AssessmentData>({ resolver: zodResolver(schema), defaultValues: defaults, mode: 'onBlur' }); const { register, reset, watch, setValue, getValues, formState: { errors } } = form
  useEffect(() => { api<Assessment>('/assessments/onboarding').then(a => { if (a.status === 'submitted') navigate('/trainee/dashboard', { replace: true }); else reset({ ...defaults, ...a.responses }) }).catch(e => { if (!(e instanceof ApiError && e.status === 404)) setMessage(e.message) }).finally(() => setLoading(false)) }, [navigate, reset])
  const steps = useMemo(() => [
    { title: 'Identity and profile', body: <div className="grid gap-4 sm:grid-cols-2"><NumberField name="age" label="Age" min={16} max={100} register={register} error={errors.age?.message}/><label className="label">Timezone<input className="field" disabled value={Intl.DateTimeFormat().resolvedOptions().timeZone} /></label></div> },
    { title: 'Fitness goal', body: <div className="grid gap-4 sm:grid-cols-2"><label className="label">Primary goal<select className="field" {...register('selected_goal')}><option value="">Select a goal</option><option value="fat_loss">Fat loss</option><option value="muscle_gain">Muscle gain</option><option value="strength">Strength</option><option value="endurance">Endurance</option><option value="general_health">General health</option><option value="athletic_performance">Athletic performance</option></select></label><NumberField name="target_weight_kg" label="Target weight" unit="kg" optional min={30} max={350} register={register}/></div> },
    { title: 'Body measurements', body: <div className="grid gap-4 sm:grid-cols-2"><NumberField name="height_cm" label="Height" unit="cm" min={100} max={250} register={register}/><NumberField name="weight_kg" label="Weight" unit="kg" min={30} max={350} register={register}/></div> },
    { title: 'Hydration', body: <><NumberField name="hydration_ml" label="Typical daily water intake" unit="ml" min={0} max={10000} register={register}/><p className="mt-3 text-sm text-black/55">The target is calculated from body weight and goal. Credit is capped at 100%; the platform does not encourage excessive intake.</p></> },
    { title: 'Sleep', body: <div className="grid gap-4 sm:grid-cols-3"><NumberField name="sleep_hours" label="Average sleep" unit="hours" min={0} max={16} register={register}/><NumberField name="sleep_quality" label="Sleep quality" unit="1–5" min={1} max={5} register={register}/><label className="label">Wake refreshed?<select className="field" value={watch('wake_refreshed') === undefined ? '' : String(watch('wake_refreshed'))} onChange={e => setValue('wake_refreshed', e.target.value === '' ? undefined : e.target.value === 'true')}><option value="">Select</option><option value="true">Yes</option><option value="false">No</option></select></label></div> },
    { title: 'Daily activity and steps', body: <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><NumberField name="daily_steps" label="Typical daily steps" min={0} max={100000} register={register}/><NumberField name="activity_minutes_weekly" label="Activity per week" unit="minutes" min={0} max={5000} register={register}/></div><fieldset><legend className="label">Activity types <span className="font-normal text-black/40">optional</span></legend><div className="mt-2 flex flex-wrap gap-2">{activityOptions.map(item => { const selected = watch('activity_types').includes(item); return <button type="button" key={item} onClick={() => setValue('activity_types', selected ? watch('activity_types').filter(v => v !== item) : [...watch('activity_types'), item])} className={`rounded-full border px-3 py-1.5 text-sm ${selected ? 'border-moss bg-mint text-moss' : 'border-black/15 bg-white'}`}>{item.replaceAll('_',' ')}</button> })}</div></fieldset></div> },
    { title: 'Workout habits and RPE', body: <div className="grid gap-4 sm:grid-cols-2"><NumberField name="workout_frequency_weekly" label="Workouts per week" min={0} max={14} register={register}/><NumberField name="average_rpe" label="Average intensity" unit="RPE 0–10" min={0} max={10} register={register}/><NumberField name="workout_duration_minutes" label="Typical duration" unit="minutes, optional" optional min={0} max={600} register={register}/><NumberField name="perceived_recovery" label="Perceived recovery" unit="1–5, optional" optional min={1} max={5} register={register}/></div> },
    { title: 'Stress', body: <><NumberField name="stress_level" label="Current stress" unit="0–10" min={0} max={10} register={register}/><p className="mt-3 text-sm text-black/55">0 means no reported stress; 10 means very high reported stress. This is a self-report, not a diagnosis.</p></> },
    { title: 'Cardiovascular information', body: <div className="space-y-4"><NumberField name="resting_heart_rate" label="Resting heart rate" unit="bpm, optional" optional min={30} max={220} register={register}/><div className="grid gap-3 sm:grid-cols-3">{([['palpitations','Palpitations'],['shortness_of_breath','Shortness of breath'],['chest_pain','Chest discomfort']] as const).map(([name,label]) => <label key={name} className="flex items-center gap-2 rounded-xl border border-black/10 p-3 text-sm font-semibold"><input type="checkbox" {...register(name)} />{label}</label>)}</div><p className="text-sm text-coral">If you have severe or worsening chest pain or breathing difficulty, seek immediate professional medical help.</p></div> },
    { title: 'Nutrition', body: <div className="grid gap-4 sm:grid-cols-3"><label className="label">Calorie mode<select className="field" {...register('calorie_mode')}><option value="">Select</option><option value="maintenance">Maintenance</option><option value="deficit">Deficit</option><option value="surplus">Surplus</option></select></label><NumberField name="calorie_target" label="Entered calorie target" optional unit="kcal" min={800} max={8000} register={register}/><NumberField name="calorie_intake" label="Estimated intake" optional unit="kcal" min={0} max={10000} register={register}/><NumberField name="protein_target_g" label="Protein target" optional unit="g" min={0} max={500} register={register}/><NumberField name="protein_intake_g" label="Protein intake" optional unit="g" min={0} max={500} register={register}/><NumberField name="fiber_g" label="Fiber" optional unit="g" min={0} max={150} register={register}/><NumberField name="fruit_servings" label="Fruit" optional unit="servings" min={0} max={30} register={register}/><NumberField name="vegetable_servings" label="Vegetables" optional unit="servings" min={0} max={30} register={register}/><NumberField name="meal_consistency" label="Meal consistency" optional unit="1–5" min={1} max={5} register={register}/></div> },
    { title: 'Review baseline', body: <Review data={getValues()} /> },
  ], [errors.age?.message, getValues, register, setValue, watch])
  async function save(next = false) { setSaving(true); setMessage(''); try { const data = schema.parse(getValues()) as AssessmentData; await api<Assessment>('/assessments/onboarding', { method: 'PUT', body: JSON.stringify({ responses: data }) }); setMessage('Draft saved'); if (next) setStep(s => Math.min(s + 1, steps.length - 1)) } catch (e) { setMessage(e instanceof z.ZodError ? 'Correct invalid values before continuing.' : e instanceof Error ? e.message : 'Could not save') } finally { setSaving(false) } }
  async function submit() { const data = getValues(); const missing = required.filter(key => data[key] === undefined || data[key] === ''); if (missing.length) { setMessage(`Complete required fields: ${missing.join(', ').replaceAll('_',' ')}`); return } setSaving(true); try { await save(false); await api<HealthIndex>('/assessments/onboarding/submit', { method: 'POST' }); navigate('/trainee/dashboard') } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not submit') } finally { setSaving(false) } }
  if (loading) return <Shell><div className="card animate-pulse">Loading your saved assessment…</div></Shell>
  return <Shell><div className="mb-6"><p className="eyebrow">Onboarding assessment</p><div className="mt-2 flex items-end justify-between"><div><h1 className="text-3xl font-black">Build your baseline</h1><p className="mt-1 text-black/60">Step {step + 1} of {steps.length}</p></div><span className="text-sm font-semibold text-moss">{Math.round((step + 1) / steps.length * 100)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full bg-moss transition-all" style={{ width: `${(step + 1) / steps.length * 100}%` }}/></div></div><section className="card"><h2 className="text-2xl font-black">{steps[step].title}</h2><div className="mt-6">{steps[step].body}</div>{message && <p role="status" className="mt-5 rounded-xl bg-mint/60 p-3 text-sm">{message}</p>}<div className="mt-7 flex flex-wrap justify-between gap-3"><button type="button" disabled={step === 0 || saving} className="btn-secondary" onClick={() => setStep(s => s - 1)}>Back</button><div className="flex gap-3"><button type="button" disabled={saving} className="btn-secondary" onClick={() => save(false)}>Save draft</button>{step < steps.length - 1 ? <button type="button" disabled={saving} className="btn-primary" onClick={() => save(true)}>Save & next</button> : <button type="button" disabled={saving} className="btn-primary" onClick={submit}>Submit baseline</button>}</div></div></section></Shell>
}

function Review({ data }: { data: AssessmentData }) { return <div><p className="text-black/60">Review your entries before submitting. You can go back to change any step.</p><dl className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(data).filter(([,v]) => v !== undefined && (!Array.isArray(v) || v.length)).map(([key,value]) => <div key={key} className="rounded-xl bg-sand p-3"><dt className="text-xs font-bold uppercase text-black/45">{key.replaceAll('_',' ')}</dt><dd className="mt-1 font-semibold">{Array.isArray(value) ? value.join(', ') : typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value)}</dd></div>)}</dl><div className="mt-5 rounded-xl border border-coral/30 bg-red-50 p-3 text-sm">Your score supports coaching decisions and is not a diagnosis or replacement for medical care.</div></div> }
