import { useEffect, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, ArrowRight, CheckCircle2, CircleStop, Plus, RefreshCw, Save, SkipForward } from 'lucide-react'
import { useParams } from 'react-router-dom'
import { api, ApiError } from '../api'
import { useAuth } from '../auth'
import { AppShell } from '../components/AppShell'
import { Badge, Button, Card, EmptyState, ErrorState, Field, LoadingState, PageHeader, SelectInput, StatusNotice, TextArea, TextInput } from '../components/ui'
import { ScheduledWorkout, TrainingAssignmentWorkspace, WorkoutSession, WorkoutSessionExercise, WorkoutSetLog } from '../types'

type SaveState = 'idle' | 'dirty' | 'saving' | 'saved' | 'error' | 'conflict'
type ActualValues = Record<string, string>
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date(`${value}T12:00:00`))

export function WorkoutExecutionPage() {
  const { scheduledWorkoutId = '' } = useParams(); const { user } = useAuth(); const cache = useQueryClient(); const [sessionId, setSessionId] = useState<string | null>(null)
  const workspace = useQuery({ queryKey: ['my-training-program'], queryFn: () => api<TrainingAssignmentWorkspace>('/trainee/program') })
  const workout = workspace.data?.scheduled_workouts.find(item => item.id === scheduledWorkoutId)
  useEffect(() => { if (workout?.workout_session_id) setSessionId(workout.workout_session_id) }, [workout?.workout_session_id])
  const session = useQuery({ queryKey: ['workout-session', sessionId], queryFn: () => api<WorkoutSession>(`/trainee/workout-sessions/${sessionId}`), enabled: Boolean(sessionId) })
  const start = useMutation({ mutationFn: () => api<WorkoutSession>(`/trainee/workouts/${scheduledWorkoutId}/start`, { method: 'POST' }), onSuccess: value => { setSessionId(value.id); cache.setQueryData(['workout-session', value.id], value) } })
  if (workspace.isLoading) return <AppShell><LoadingState label="Loading workout" /></AppShell>
  if (workspace.error) return <AppShell><ErrorState title="Workout unavailable" description={workspace.error.message} onRetry={() => workspace.refetch()} /></AppShell>
  if (!workout) return <AppShell><EmptyState title="Workout not found" description="This scheduled workout is not available in your Program." /></AppShell>
  if (sessionId && session.isLoading) return <AppShell><LoadingState label="Loading saved workout progress" /></AppShell>
  if (session.error) return <AppShell><ErrorState title="Saved workout unavailable" description={session.error.message} onRetry={() => session.refetch()} /></AppShell>
  if (session.data) return <SessionExperience session={session.data} onChange={value => cache.setQueryData(['workout-session', value.id], value)} onReload={() => session.refetch()} demo={Boolean(user?.is_demo)} />
  return <ScheduledOverview workout={workout} programName={workspace.data?.current_assignment?.program_name ?? 'Assigned Program'} programVersion={workspace.data?.current_assignment?.program_version_number ?? 1} demo={Boolean(user?.is_demo)} starting={start.isPending} error={start.error} onStart={() => start.mutate()} />
}

function ScheduledOverview({ workout, programName, programVersion, demo, starting, error, onStart }: { workout: ScheduledWorkout; programName: string; programVersion: number; demo: boolean; starting: boolean; error: Error | null; onStart: () => void }) {
  const blocked = workout.status === 'cancelled' || workout.status === 'superseded'
  return <AppShell><div className="mx-auto max-w-3xl space-y-5"><PageHeader eyebrow="FitIntel 360 · Workout" title={workout.workout_template_version.name} description={`${programName} · version ${programVersion} · ${formatDate(workout.scheduled_date)}`} />{demo && <StatusNotice tone="info" title="Demo workspace — changes are disabled.">Inspect this scheduled workout without starting or changing it.</StatusNotice>}{blocked && <StatusNotice tone="attention" title={`Workout ${workout.status}`}>This schedule entry cannot be started.</StatusNotice>}{error && <StatusNotice tone="risk" title="Workout could not start">{error.message}</StatusNotice>}<Card><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Duration" value={workout.planned_duration_minutes ? `${workout.planned_duration_minutes} min` : 'Not set'} /><Metric label="Target RPE" value={workout.target_session_rpe ?? 'Not set'} /><Metric label="Exercises" value={workout.workout_template_version.exercise_count} /><Metric label="Status" value={workout.status.replace('_', ' ')} /></div>{workout.trainee_instructions && <p className="mt-5 text-sm leading-6 text-secondary">{workout.trainee_instructions}</p>}<Button className="mt-6 w-full sm:w-auto" loading={starting} disabled={demo || blocked || workout.status !== 'scheduled'} onClick={onStart}>Start workout</Button></Card></div></AppShell>
}

function SessionExperience({ session, onChange, onReload, demo }: { session: WorkoutSession; onChange: (value: WorkoutSession) => void; onReload: () => void; demo: boolean }) {
  const [index, setIndex] = useState(0); const [conflict, setConflict] = useState(false); const exercise = session.exercises[index]; const terminal = session.status !== 'in_progress'
  const completedSets = session.exercises.flatMap(item => item.sets).filter(item => item.status !== 'planned').length
  const totalSets = session.exercises.flatMap(item => item.sets).length
  if (terminal) return <CompletionSummary session={session} />
  return <AppShell><div className="mx-auto max-w-3xl space-y-5"><PageHeader eyebrow="FitIntel 360 · Active workout" title={session.workout_name} description={`${session.program_name} · version ${session.program_version_number} · ${formatDate(session.scheduled_date)}`} />{demo && <StatusNotice tone="info" title="Demo workspace — changes are disabled.">This synthetic execution example is read-only.</StatusNotice>}{conflict && <StatusNotice tone="attention" title="Workout updated elsewhere">Your unsaved entries remain on this page. Reload the latest session before saving again.<Button variant="secondary" className="mt-3" onClick={() => { onReload(); setConflict(false) }}><RefreshCw aria-hidden="true" className="size-4" />Reload latest session</Button></StatusNotice>}<Card><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-semibold">{completedSets} of {totalSets} sets resolved</p><p className="mt-1 text-xs text-muted">Session revision {session.revision}</p></div><Badge tone="info">In progress</Badge></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-elevated"><div className="h-full bg-primary" style={{ width: `${totalSets ? (completedSets / totalSets) * 100 : 0}%` }} /></div></Card>{exercise && <ExercisePanel key={exercise.id} session={session} exercise={exercise} demo={demo} onChange={onChange} onConflict={() => setConflict(true)} />}<div className="flex items-center justify-between gap-3"><Button variant="secondary" disabled={index === 0} onClick={() => setIndex(value => value - 1)}><ArrowLeft aria-hidden="true" className="size-4" />Previous</Button><span className="text-xs font-semibold text-muted">Exercise {index + 1} of {session.exercises.length}</span><Button variant="secondary" disabled={index === session.exercises.length - 1} onClick={() => setIndex(value => value + 1)}>Next<ArrowRight aria-hidden="true" className="size-4" /></Button></div><FinishPanel session={session} demo={demo} onChange={onChange} onConflict={() => setConflict(true)} /></div></AppShell>
}

function ExercisePanel({ session, exercise, demo, onChange, onConflict }: { session: WorkoutSession; exercise: WorkoutSessionExercise; demo: boolean; onChange: (value: WorkoutSession) => void; onConflict: () => void }) {
  const [reason, setReason] = useState('time_constraint'); const [note, setNote] = useState(''); const [message, setMessage] = useState('')
  const skip = useMutation({ mutationFn: () => api<WorkoutSession>(`/trainee/workout-sessions/${session.id}/exercises/${exercise.id}/skip`, { method: 'POST', body: JSON.stringify({ expected_session_revision: session.revision, reason, note: note || null }) }), onSuccess: onChange, onError: caught => handleError(caught, setMessage, onConflict) })
  const add = useMutation({ mutationFn: () => api<WorkoutSession>(`/trainee/workout-sessions/${session.id}/sets`, { method: 'POST', body: JSON.stringify({ expected_session_revision: session.revision, idempotency_key: crypto.randomUUID(), workout_session_exercise_id: exercise.id, set_type: 'working', status: 'planned' }) }), onSuccess: onChange, onError: caught => handleError(caught, setMessage, onConflict) })
  return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-primary">{exercise.section.replace('_', ' ')}</p><h2 className="mt-1 text-2xl font-semibold">{exercise.exercise_name}</h2><p className="mt-1 text-sm text-secondary">{exercise.tracking_mode.replaceAll('_', ' ')}</p></div><Badge tone={exercise.status === 'skipped' ? 'attention' : exercise.status === 'completed' ? 'positive' : 'neutral'}>{exercise.status.replace('_', ' ')}</Badge></div>{exercise.trainee_instructions && <p className="mt-4 text-sm leading-6 text-secondary">{exercise.trainee_instructions}</p>}{exercise.safety_cues.length > 0 && <div className="mt-4 rounded-xl bg-elevated p-4"><p className="text-xs font-bold uppercase tracking-wider text-muted">Safety cues</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-secondary">{exercise.safety_cues.map(cue => <li key={cue}>{cue}</li>)}</ul></div>}<div className="mt-5 space-y-4">{exercise.sets.map(item => <SetEditor key={item.id} session={session} item={item} demo={demo || exercise.status === 'skipped'} onChange={onChange} onConflict={onConflict} />)}</div>{message && <p role="alert" className="mt-3 text-sm text-risk">{message}</p>}<div className="mt-5 flex flex-wrap gap-3"><Button variant="secondary" disabled={demo || exercise.status === 'skipped'} loading={add.isPending} onClick={() => add.mutate()}><Plus aria-hidden="true" className="size-4" />Add set</Button></div><div className="mt-5 border-t pt-5"><Field label="Skip reason">{({ id }) => <SelectInput id={id} value={reason} disabled={demo || exercise.status === 'skipped'} onChange={event => setReason(event.target.value)}><option value="time_constraint">Time constraint</option><option value="equipment_unavailable">Equipment unavailable</option><option value="recovery_concern">Recovery concern</option><option value="discomfort">Discomfort</option><option value="coach_instruction">Coach instruction</option><option value="other">Other</option></SelectInput>}</Field><Field label="Optional skip note">{({ id }) => <TextArea id={id} maxLength={500} value={note} disabled={demo || exercise.status === 'skipped'} onChange={event => setNote(event.target.value)} />}</Field><Button variant="danger" disabled={demo || exercise.status === 'skipped'} loading={skip.isPending} onClick={() => skip.mutate()}><SkipForward aria-hidden="true" className="size-4" />Skip exercise</Button></div></Card>
}

function SetEditor({ session, item, demo, onChange, onConflict }: { session: WorkoutSession; item: WorkoutSetLog; demo: boolean; onChange: (value: WorkoutSession) => void; onConflict: () => void }) {
  const [values, setValues] = useState<ActualValues>(() => actualValues(item)); const [state, setState] = useState<SaveState>('idle'); const [message, setMessage] = useState('')
  const update = useMutation({ mutationFn: (status: 'completed' | 'skipped') => api<WorkoutSession>(`/trainee/workout-sessions/${session.id}/sets/${item.id}`, { method: 'PUT', body: JSON.stringify({ expected_session_revision: session.revision, status, ...(status === 'completed' ? payload(values) : {}) }) }), onMutate: () => { setState('saving'); setMessage('') }, onSuccess: value => { setState('saved'); onChange(value) }, onError: caught => { if (caught instanceof ApiError && caught.status === 409) { setState('conflict'); onConflict() } else { setState('error'); setMessage(caught instanceof Error ? caught.message : 'Set could not be saved.') } } })
  const change = (key: string, value: string) => { setValues(current => ({ ...current, [key]: value })); setState('dirty') }
  return <div className="rounded-xl border bg-elevated/40 p-4"><div className="flex items-center justify-between gap-2"><div><p className="font-semibold">Set {item.set_number} · {item.set_type.replace('_', ' ')}</p><p className="mt-1 text-xs text-muted">{plannedLabel(item)}</p></div><Badge tone={item.status === 'completed' ? 'positive' : item.status === 'skipped' ? 'attention' : 'neutral'}>{item.status}</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{trackingFields(item, values, change, demo)}</div><p aria-live="polite" className="mt-3 text-xs font-semibold text-muted">{state === 'dirty' ? 'Unsaved changes' : state === 'saving' ? 'Saving…' : state === 'saved' ? 'Saved' : state === 'conflict' ? 'Revision conflict' : state === 'error' ? message : 'Ready'}</p><div className="mt-3 flex flex-wrap gap-2"><Button disabled={demo} loading={update.isPending} onClick={() => update.mutate('completed')}><Save aria-hidden="true" className="size-4" />Save completed set</Button><Button variant="secondary" disabled={demo} onClick={() => update.mutate('skipped')}>Skip set</Button></div></div>
}

function FinishPanel({ session, demo, onChange, onConflict }: { session: WorkoutSession; demo: boolean; onChange: (value: WorkoutSession) => void; onConflict: () => void }) {
  const [duration, setDuration] = useState(''); const [rpe, setRpe] = useState(''); const [note, setNote] = useState(''); const [confirmed, setConfirmed] = useState(false); const [endReason, setEndReason] = useState('time_constraint'); const [message, setMessage] = useState('')
  const complete = useMutation({ mutationFn: () => api<WorkoutSession>(`/trainee/workout-sessions/${session.id}/complete`, { method: 'POST', body: JSON.stringify({ expected_session_revision: session.revision, actual_duration_minutes: Number(duration), session_rpe: Number(rpe), trainee_note: note || null, confirmed }) }), onSuccess: onChange, onError: caught => handleError(caught, setMessage, onConflict) })
  const end = useMutation({ mutationFn: () => api<WorkoutSession>(`/trainee/workout-sessions/${session.id}/end-incomplete`, { method: 'POST', body: JSON.stringify({ expected_session_revision: session.revision, reason: endReason, note: note || null }) }), onSuccess: onChange, onError: caught => handleError(caught, setMessage, onConflict) })
  return <Card><h2 className="text-xl font-semibold">Finish workout</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Actual duration (minutes)">{({ id }) => <TextInput id={id} type="number" min="1" max="1440" value={duration} disabled={demo} onChange={event => setDuration(event.target.value)} />}</Field><Field label="Session RPE (0–10)">{({ id }) => <TextInput id={id} type="number" min="0" max="10" step="0.5" value={rpe} disabled={demo} onChange={event => setRpe(event.target.value)} />}</Field></div><Field label="Trainee note">{({ id }) => <TextArea id={id} maxLength={2000} value={note} disabled={demo} onChange={event => setNote(event.target.value)} />}</Field><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={confirmed} disabled={demo} onChange={event => setConfirmed(event.target.checked)} />I confirm this workout is ready to complete.</label>{message && <p role="alert" className="mt-3 text-sm text-risk">{message}</p>}<Button className="mt-4 w-full sm:w-auto" disabled={demo || !duration || !rpe || !confirmed} loading={complete.isPending} onClick={() => complete.mutate()}><CheckCircle2 aria-hidden="true" className="size-4" />Complete workout</Button><div className="mt-6 border-t pt-5"><Field label="Reason for ending incomplete">{({ id }) => <SelectInput id={id} value={endReason} disabled={demo} onChange={event => setEndReason(event.target.value)}><option value="time_constraint">Time constraint</option><option value="recovery_concern">Recovery concern</option><option value="discomfort">Discomfort</option><option value="equipment_issue">Equipment issue</option><option value="other">Other</option></SelectInput>}</Field><Button variant="danger" disabled={demo} loading={end.isPending} onClick={() => end.mutate()}><CircleStop aria-hidden="true" className="size-4" />End workout incomplete</Button></div></Card>
}

function CompletionSummary({ session }: { session: WorkoutSession }) { const exercises = session.exercises; const sets = exercises.flatMap(item => item.sets); return <AppShell><div className="mx-auto max-w-3xl space-y-5"><PageHeader eyebrow="FitIntel 360 · Workout summary" title={session.workout_name} description={`${session.program_name} · ${formatDate(session.scheduled_date)}`} /><StatusNotice tone={session.status === 'completed' ? 'positive' : 'attention'} title={session.status === 'completed' ? 'Workout completed' : 'Workout ended incomplete'}>This execution is now immutable.</StatusNotice><Card><div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><Metric label="Completed exercises" value={exercises.filter(item => item.status === 'completed').length} /><Metric label="Skipped exercises" value={exercises.filter(item => item.status === 'skipped').length} /><Metric label="Completed sets" value={sets.filter(item => item.status === 'completed').length} /><Metric label="Skipped sets" value={sets.filter(item => item.status === 'skipped').length} /><Metric label="Duration" value={session.actual_duration_minutes ? `${session.actual_duration_minutes} min` : 'Not recorded'} /><Metric label="Session RPE" value={session.session_rpe ?? 'Not recorded'} /></div>{session.trainee_note && <p className="mt-5 text-sm leading-6 text-secondary">{session.trainee_note}</p>}</Card></div></AppShell> }
function Metric({ label, value }: { label: string; value: string | number }) { return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-semibold capitalize">{value}</dd></div> }
function actualValues(item: WorkoutSetLog): ActualValues { return Object.fromEntries(['actual_repetitions', 'actual_load_original_value', 'actual_load_original_unit', 'actual_assistance_original_value', 'actual_assistance_original_unit', 'actual_duration_seconds', 'actual_distance_value', 'actual_distance_unit', 'actual_rpe', 'actual_rir'].map(key => [key, String(item[key as keyof WorkoutSetLog] ?? '')])) }
function payload(values: ActualValues) { return Object.fromEntries(Object.entries(values).filter(([, value]) => value !== '').map(([key, value]) => [key, key.endsWith('_unit') ? value : Number(value)])) }
function plannedLabel(item: WorkoutSetLog) { if (item.planned_repetitions_min) return `${item.planned_repetitions_min}–${item.planned_repetitions_max} reps${item.planned_load_original_value ? ` · ${item.planned_load_original_value} ${item.planned_load_original_unit}` : ''}${item.planned_assistance_original_value ? ` · ${item.planned_assistance_original_value} ${item.planned_assistance_original_unit} assistance` : ''}`; if (item.planned_distance_value) return `${item.planned_distance_value} ${item.planned_distance_unit} · ${item.planned_duration_seconds}s`; return item.planned_duration_seconds ? `${item.planned_duration_seconds}s` : 'Trainee-added set' }
function trackingFields(item: WorkoutSetLog, values: ActualValues, change: (key: string, value: string) => void, disabled: boolean) { const input = (key: string, label: string, props: Record<string, string> = {}) => <Field key={key} label={label}>{({ id }) => <TextInput id={id} type="number" value={values[key]} disabled={disabled} onChange={event => change(key, event.target.value)} {...props} />}</Field>; const unit = (key: string, label: string, options: string[]) => <Field key={key} label={label}>{({ id }) => <SelectInput id={id} value={values[key]} disabled={disabled} onChange={event => change(key, event.target.value)}><option value="">Select unit</option>{options.map(value => <option key={value} value={value}>{value}</option>)}</SelectInput>}</Field>; const fields = []; if (['repetitions_and_load', 'repetitions_only', 'bodyweight_or_assisted_repetitions'].includes(item.tracking_mode)) fields.push(input('actual_repetitions', 'Actual repetitions', { min: '1' })); if (item.tracking_mode === 'repetitions_and_load') fields.push(input('actual_load_original_value', 'External load', { min: '0', step: '0.001' }), unit('actual_load_original_unit', 'Load unit', ['kg', 'lb'])); if (item.tracking_mode === 'bodyweight_or_assisted_repetitions') fields.push(input('actual_assistance_original_value', 'Assistance (optional)', { min: '0', step: '0.001' }), unit('actual_assistance_original_unit', 'Assistance unit', ['kg', 'lb'])); if (['duration', 'distance_and_duration'].includes(item.tracking_mode)) fields.push(input('actual_duration_seconds', 'Duration (seconds)', { min: '1' })); if (item.tracking_mode === 'distance_and_duration') fields.push(input('actual_distance_value', 'Distance', { min: '0', step: '0.001' }), unit('actual_distance_unit', 'Distance unit', ['meters', 'kilometers', 'miles'])); fields.push(input('actual_rpe', 'RPE (optional)', { min: '0', max: '10', step: '0.5' })); if (['repetitions_only', 'bodyweight_or_assisted_repetitions'].includes(item.tracking_mode)) fields.push(input('actual_rir', 'RIR (optional)', { min: '0', max: '10', step: '0.5' })); return fields }
function handleError(caught: unknown, setMessage: (value: string) => void, onConflict: () => void) { if (caught instanceof ApiError && caught.status === 409 && caught.details.code === 'session_revision_conflict') onConflict(); else setMessage(caught instanceof Error ? caught.message : 'The workout could not be updated.') }
