import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from './auth'
import { HealthIndex } from './types'

export function Shell({ children }: { children: React.ReactNode }) {
  const { user, logout } = useAuth(); const navigate = useNavigate()
  return <><header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link to={user?.role === 'coach' ? '/coach/dashboard' : '/trainee/dashboard'} className="font-black tracking-tight">FITNESS <span className="text-moss">INTELLIGENCE</span></Link>{user && <div className="flex items-center gap-4 text-sm"><span className="hidden sm:inline">{user.first_name} · {user.role}</span><button className="font-semibold text-moss" onClick={() => { logout(); navigate('/login') }}>Sign out</button></div>}</div></header><main className="mx-auto max-w-6xl px-5 py-8">{children}</main></>
}
export function StateCard({ title, children }: { title: string; children: React.ReactNode }) { return <div className="card mx-auto max-w-xl text-center"><h2 className="text-xl font-bold">{title}</h2><div className="mt-2 text-black/65">{children}</div></div> }
export function ScoreView({ health, coachView = false }: { health: HealthIndex; coachView?: boolean }) {
  return <div className="space-y-6"><section className="grid gap-5 md:grid-cols-[0.75fr_1.25fr]"><div className="card bg-ink text-white"><p className="eyebrow !text-mint">Baseline health index</p><div className="mt-4 flex items-end gap-3"><span className="text-7xl font-black">{health.overall_score}</span><span className="pb-2 text-xl text-white/60">/100</span></div><p className="mt-3 text-2xl font-bold text-mint">{health.band}</p><p className="mt-6 text-sm text-white/60">Calculated {new Date(health.calculated_at).toLocaleDateString()} · {health.scoring_version}</p></div><div className="card"><p className="eyebrow">Component breakdown</p><div className="mt-4 space-y-4">{health.components.map(c => <div key={c.key}><div className="mb-1 flex justify-between text-sm"><span className="font-semibold capitalize">{c.key.replaceAll('_', ' ')}</span><span>{c.normalized_score} × {c.weight}% = {c.weighted_contribution}</span></div><div className="h-2 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-moss" style={{ width: `${c.normalized_score}%` }} /></div><p className="mt-1 text-xs text-black/55">{c.explanation}</p></div>)}</div></div></section><section className="grid gap-5 md:grid-cols-2"><div className="card"><h2 className="text-xl font-bold">Recommended next steps</h2>{health.recommendations.length ? <ul className="mt-4 space-y-3">{health.recommendations.map(r => <li key={r.key} className="rounded-xl bg-mint/60 p-3"><span className="text-xs font-bold uppercase text-moss">{r.category} · {r.priority}</span><p className="mt-1 text-sm">{r.recommended_action}</p>{r.safety_text && <p className="mt-1 text-xs text-black/55">{r.safety_text}</p>}</li>)}</ul> : <p className="mt-3 text-black/60">No priority recommendations from this baseline.</p>}</div><div className="card"><h2 className="text-xl font-bold">Review notices</h2>{health.risk_flags.length ? <div className="mt-4 space-y-3">{health.risk_flags.map(a => <div key={a.rule_key} className={`rounded-xl border p-3 ${a.severity === 'urgent' ? 'border-coral bg-red-50' : 'border-amber-300 bg-amber-50'}`}><span className="text-xs font-bold uppercase">{a.severity}</span><h3 className="font-bold">{a.title}</h3><p className="mt-1 text-sm">{a.explanation}</p><p className="mt-2 text-sm font-semibold">{a.recommended_action}</p></div>)}</div> : <p className="mt-3 text-black/60">No onboarding rules were triggered.</p>}<p className="mt-4 text-xs text-black/50">{coachView ? 'Use these notices for review; they are not diagnoses.' : 'This platform does not diagnose or replace medical care.'}</p></div></section></div>
}
